### ISSUE TITLE
python SDK update

### ISSUE THREAD

**Issue by zaza81** [codenotary/immudb-py#29]
- [x]  Some functions are named reverse than in Go SDK.
- [ ] We should get rid of binary input parameters (i.e. b’test’)
- [ ] Publish to conda as well
- [ ] Example on list users not working 
- [ ] Example on how to execute sql queries, list tables, list databases 
- [ ] Default port in examples should be the same default port for immudb
- [ ] Improve output messages: okay statuses after connection, or better output when inserting rows.

**Comment by tomekkolo** [comment]
closing, updated immudb-py is released.
