### ISSUE TITLE
stale files in pip distribution

### ISSUE THREAD

**Issue by mabmayer** [codenotary/immudb-py#30]
The pip distribution has some extra files which are no longer in master:
handler/safeGet.py
handler/safeSet.py
consistency.py
inclusion.py
item.py
proofs.py

**Comment by SimoneLazzaris** [comment]
Fixed in commit 0b3ff60. Apparently, if you don't purge the `/build` directory, artifacts from the lib subdirectory finds their way to the release.

**Comment by SimoneLazzaris** [comment]
Next pip package will be without them
