### ISSUE TITLE
VerificationException with immudb 1.2.1

### ISSUE THREAD

**Issue by ankane** [codenotary/immudb-py#33]
Hi, I wanted to report a `immudb.exceptions.VerificationException` exception when using `verifiedSet` with the latest release (1.1.0). Here's a script to reproduce:

```python
from immudb import ImmudbClient

client = ImmudbClient()
client.login("immudb", "immudb")
client.verifiedSet(b"hello", b"world")
```

Examples from [immudb-client-examples](https://github.com/codenotary/immudb-client-examples) that use `verifiedSet` raise the same exception.

Looking at the [release notes](https://github.com/codenotary/immudb/releases/tag/v1.2.1) for immudb 1.2.1, it looks like there's a breaking change that may be responsible.

> Introduction of the entry metadata requires a slightly modified version of the proof that also needs to consider such metadata. An updated version of the SDK will be needed to correctly verify proofs for new entries.

**Comment by mabmayer** [comment]
Hi Andrew, please have a look at our new release of immudb-py. It should fix the issue. If not, please reopen.

**Comment by ankane** [comment]
That fixed it. Thanks @mabmayer!
